import sys
import qdarkstyle
from PyQt5 import QtWidgets
from ui import Ui_MainWindow


# class Ui_MainWindow(object):
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName("MainWindow")
#         MainWindow.resize(1200, 500)
#         MainWindow.setMinimumSize(QtCore.QSize(1250, 500))
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setStyleSheet("QLabel {border: 1px solid white; border-radius: 6px; }")
#         self.centralwidget.setObjectName("centralwidget")
#         self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
#         self.horizontalLayout.setObjectName("horizontalLayout")
#         self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
#         self.scrollArea.setStyleSheet("QScrollArea { border: none; }")
#         self.scrollArea.setWidgetResizable(True)
#         self.scrollArea.setObjectName("scrollArea")
#         self.scrollAreaWidgetContents = QtWidgets.QWidget()
#         self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1182, 441))
#         self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
#         self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
#         self.gridLayout.setContentsMargins(3, 0, 3, 0)
#         self.gridLayout.setObjectName("gridLayout")
#         self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents)
#         self.line.setFrameShape(QtWidgets.QFrame.HLine)
#         self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
#         self.line.setObjectName("line")
#         self.gridLayout.addWidget(self.line, 1, 0, 1, 5)
#         self.pushButton_4 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
#         self.pushButton_4.setMinimumSize(QtCore.QSize(130, 30))
#         self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 30))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         self.pushButton_4.setFont(font)
#         self.pushButton_4.setObjectName("pushButton_4")
#         self.gridLayout.addWidget(self.pushButton_4, 2, 4, 1, 1)
#         self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
#         self.label.setMinimumSize(QtCore.QSize(600, 30))
#         self.label.setMaximumSize(QtCore.QSize(16777215, 30))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         self.label.setFont(font)
#         self.label.setStyleSheet("")
#         self.label.setObjectName("label")
#         self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
#         self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
#         self.pushButton.setMinimumSize(QtCore.QSize(130, 30))
#         self.pushButton.setMaximumSize(QtCore.QSize(130, 30))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         self.pushButton.setFont(font)
#         self.pushButton.setObjectName("pushButton")
#         self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
#         self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
#         self.label_2.setMinimumSize(QtCore.QSize(110, 30))
#         self.label_2.setMaximumSize(QtCore.QSize(120, 30))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         self.label_2.setFont(font)
#         self.label_2.setAlignment(QtCore.Qt.AlignCenter)
#         self.label_2.setObjectName("label_2")
#         self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
#         self.pushButton_2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
#         self.pushButton_2.setMinimumSize(QtCore.QSize(130, 30))
#         self.pushButton_2.setMaximumSize(QtCore.QSize(16777215, 30))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         self.pushButton_2.setFont(font)
#         self.pushButton_2.setObjectName("pushButton_2")
#         self.gridLayout.addWidget(self.pushButton_2, 2, 2, 1, 1)
#         self.pushButton_3 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
#         self.pushButton_3.setMinimumSize(QtCore.QSize(130, 30))
#         self.pushButton_3.setMaximumSize(QtCore.QSize(16777215, 30))
#         font = QtGui.QFont()
#         font.setPointSize(11)
#         self.pushButton_3.setFont(font)
#         self.pushButton_3.setObjectName("pushButton_3")
#         self.gridLayout.addWidget(self.pushButton_3, 2, 3, 1, 1)
#         spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
#         self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
#         self.scrollArea.setWidget(self.scrollAreaWidgetContents)
#         self.horizontalLayout.addWidget(self.scrollArea)
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
#         self.menubar.setObjectName("menubar")
#         self.menuMenu = QtWidgets.QMenu(self.menubar)
#         self.menuMenu.setObjectName("menuMenu")
#         MainWindow.setMenuBar(self.menubar)
#         self.actionAdd_new_Script = QtWidgets.QAction(MainWindow)
#         self.actionAdd_new_Script.setObjectName("actionAdd_new_Script")
#         self.actionCheck_for_Updates = QtWidgets.QAction(MainWindow)
#         self.actionCheck_for_Updates.setObjectName("actionCheck_for_Updates")
#         self.actionQuit = QtWidgets.QAction(MainWindow)
#         self.actionQuit.setObjectName("actionQuit")
#         self.menuMenu.addAction(self.actionAdd_new_Script)
#         self.menuMenu.addAction(self.actionCheck_for_Updates)
#         self.menuMenu.addSeparator()
#         self.menuMenu.addAction(self.actionQuit)
#         self.menubar.addAction(self.menuMenu.menuAction())
#
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate("MainWindow", "GarryCron"))
#         self.pushButton_4.setText(_translate("MainWindow", "Delete"))
#         self.label.setText(_translate("MainWindow", "ThisIsAPythonScriptAndBecomeVeryLongSinceItsAlsoThePathOrIImplementANameInstead.py"))
#         self.pushButton.setText(_translate("MainWindow", "Add new Script"))
#         self.label_2.setText(_translate("MainWindow", "00:00:00:00"))
#         self.pushButton_2.setText(_translate("MainWindow", "Run now"))
#         self.pushButton_3.setText(_translate("MainWindow", "Edit"))
#         self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
#         self.actionAdd_new_Script.setText(_translate("MainWindow", "Add new Script"))
#         self.actionCheck_for_Updates.setText(_translate("MainWindow", "Check for Updates"))
#         self.actionQuit.setText(_translate("MainWindow", "Quit"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
