# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaCron-EntryWidgetV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1215, 38)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btn_run = QtWidgets.QPushButton(Form)
        self.btn_run.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_run.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_run.setFont(font)
        self.btn_run.setObjectName("btn_run")
        self.gridLayout.addWidget(self.btn_run, 0, 2, 1, 1)
        self.btn_edit = QtWidgets.QPushButton(Form)
        self.btn_edit.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_edit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_edit.setFont(font)
        self.btn_edit.setObjectName("btn_edit")
        self.gridLayout.addWidget(self.btn_edit, 0, 4, 1, 1)
        self.lbl_name = QtWidgets.QLabel(Form)
        self.lbl_name.setMinimumSize(QtCore.QSize(600, 30))
        self.lbl_name.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_name.setFont(font)
        self.lbl_name.setStyleSheet("")
        self.lbl_name.setObjectName("lbl_name")
        self.gridLayout.addWidget(self.lbl_name, 0, 0, 1, 1)
        self.btn_delete = QtWidgets.QPushButton(Form)
        self.btn_delete.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_delete.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_delete.setFont(font)
        self.btn_delete.setObjectName("btn_delete")
        self.gridLayout.addWidget(self.btn_delete, 0, 3, 1, 1)
        self.lbl_interval = QtWidgets.QLabel(Form)
        self.lbl_interval.setMinimumSize(QtCore.QSize(110, 30))
        self.lbl_interval.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_interval.setFont(font)
        self.lbl_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_interval.setObjectName("lbl_interval")
        self.gridLayout.addWidget(self.lbl_interval, 0, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_run.setText(_translate("Form", "Run now"))
        self.btn_edit.setText(_translate("Form", "Edit"))
        self.lbl_name.setText(_translate("Form", "ThisIsAPythonScriptpy"))
        self.btn_delete.setText(_translate("Form", "Delete"))
        self.lbl_interval.setText(_translate("Form", "00:00:00:00"))
