# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaCron-MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/macaron_flaticon-com.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QLabel {\n"
"border: 1px solid black;\n"
"border-color: white;\n"
"}\n"
"\n"
"QScrollArea {\n"
"border: None;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_addScript = QtWidgets.QPushButton(self.centralwidget)
        self.btn_addScript.setMinimumSize(QtCore.QSize(120, 30))
        self.btn_addScript.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_addScript.setFont(font)
        self.btn_addScript.setObjectName("btn_addScript")
        self.verticalLayout.addWidget(self.btn_addScript)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1180, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 3, 0, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.menuStyles = QtWidgets.QMenu(self.menubar)
        self.menuStyles.setObjectName("menuStyles")
        MainWindow.setMenuBar(self.menubar)
        self.menu_action_add = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/assets/icons/plus-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.menu_action_add.setIcon(icon1)
        self.menu_action_add.setStatusTip("")
        self.menu_action_add.setObjectName("menu_action_add")
        self.menu_action_update = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/assets/icons/compile.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.menu_action_update.setIcon(icon2)
        self.menu_action_update.setObjectName("menu_action_update")
        self.menu_action_exit = QtWidgets.QAction(MainWindow)
        self.menu_action_exit.setIcon(icon1)
        self.menu_action_exit.setObjectName("menu_action_exit")
        self.menu_theme_dark = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/assets/icons/light-bulb-off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_theme_dark.setIcon(icon3)
        self.menu_theme_dark.setObjectName("menu_theme_dark")
        self.menu_theme_light = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/assets/icons/light-bulb.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menu_theme_light.setIcon(icon4)
        self.menu_theme_light.setObjectName("menu_theme_light")
        self.menuMenu.addAction(self.menu_action_add)
        self.menuMenu.addAction(self.menu_action_update)
        self.menuMenu.addSeparator()
        self.menuMenu.addAction(self.menu_action_exit)
        self.menuStyles.addAction(self.menu_theme_dark)
        self.menuStyles.addAction(self.menu_theme_light)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.menuStyles.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MaCron"))
        self.btn_addScript.setText(_translate("MainWindow", "Add new Script"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.menuStyles.setTitle(_translate("MainWindow", "Styles"))
        self.menu_action_add.setText(_translate("MainWindow", "Add new Script"))
        self.menu_action_add.setIconText(_translate("MainWindow", "Add new Script"))
        self.menu_action_add.setToolTip(_translate("MainWindow", "Add new Script"))
        self.menu_action_update.setText(_translate("MainWindow", "Check for Updates"))
        self.menu_action_exit.setText(_translate("MainWindow", "Quit"))
        self.menu_theme_dark.setText(_translate("MainWindow", "Dark Theme"))
        self.menu_theme_light.setText(_translate("MainWindow", "Light Theme"))
import ui_resources_rc
